[project]
name = "mids-datasci200-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fitz>=0.0.1.dev2",
    "ipykernel>=7.1.0",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "pandoc>=2.4",
    "pypdf>=6.14.2",
    "pypdf2>=3.0.1",
]

[tool.ruff]
line-length = 120

